[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["denis@pagebox.io"]
edition = "2021"

[dependencies]
regex = "1.5"
log = "0.4"
env_logger = "0.9"
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
anyhow = "1.0"
